package com.quicktutorialz.learnmicroservices.XmlVsJsonData.entities;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})   //else it gives me error asking for one Task
@Entity @Table(name="tasks")
@AllArgsConstructor @NoArgsConstructor
@XmlRootElement                                                  //so I can get output data in XML too!
public class Task {

    @Id @GeneratedValue @Column(name="ID")
    @Getter @Setter
    private Integer id;                         //it can be null because it's autogenerated and I don't insert it for databinding

    @Column(name="TITLE")
    @Getter @Setter
    @NotBlank
    private String title;

    @Column(name="DATE")
    @Getter @Setter
    private Date date;                          //it can be null because I use prepersist and I don't insert it for databinding

    @Column(name="USER_ID")
    @Getter @Setter
    @NotNull
    private Integer fkUser;

    @PrePersist
    private void setDate(){
        this.date = new Date();
    }



}
